import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import {gunzipSync} from 'node:zlib';
import {beforeAll,afterAll,beforeEach,afterEach,it,expect} from 'vitest';
let db:PGlite;
const owner='10000000-0000-0000-0000-000000000001';
async function one(sql:string,args:unknown[]=[]):Promise<any>{return Object.values((await db.query(sql,args)).rows[0] as object)[0];}
async function order(denomination='USD',usd=40,ves=0){const o=await one('insert into orders(is_walk_in) values(true) returning id');await one("select add_service_priced($1,'WORKSHOP','Trabajo pactado',40,40,null,false,$2)",[o,denomination]);if(usd)await one("select add_payment($1,'CASH_USD',$2)",[o,usd]);if(ves)await one("select add_payment($1,'CASH_VES',$2)",[o,ves]);return o;}
async function review(){return one('select payroll_review(current_date)');}
async function settle(){const work=await review();const emp=work[0].employee_id;const expected=work.filter((w:any)=>w.employee_id===emp&&w.decision!=='HOLD').sort((a:any,b:any)=>a.id.localeCompare(b.id)).map((w:any)=>({id:w.id,version:w.version}));return one('select payroll_settle($1,current_date-6,current_date,$2)',[emp,JSON.stringify({work:expected,fixed_ref:Number(await one("select coalesce((select value from compensation_rules where employee_id=$1 and rule_type='FIXED_WEEKLY' and valid_from<=current_date and (valid_to is null or valid_to>=current_date) order by valid_from desc limit 1),0)",[emp])),adjustments:[]})]);}
async function rejects(fn:()=>Promise<any>,pattern:RegExp){await db.exec('savepoint rejected');let error:any;try{await fn();}catch(e){error=e;}await db.exec('rollback to rejected');expect(error?.message).toMatch(pattern);}
beforeAll(async()=>{db=new PGlite();await db.exec(gunzipSync(readFileSync('tests/fixtures/production-structure.sql.gz')).toString());await db.exec('set check_function_bodies=on');await db.exec(readFileSync('supabase/migrations/20260924145617_usd_pricing_payroll_review.sql','utf8'));await db.exec(`insert into auth.users values('${owner}','lubricenterc@gmail.com',now());select set_config('request.jwt.claim.sub','${owner}',false);insert into employees(code,name) values('CHEO','Cheo'),('ALEXIS','Alexis');insert into financial_accounts(code,name,currency,account_type) values('CASH_USD','Caja USD','USD','CASH'),('CASH_VES','Caja Bs','VES','CASH');insert into exchange_rates(rate_type,value,effective_at) values('BCV',100,'2026-01-01'),('OPERATIVE',200,'2026-01-01');`);},120000);
afterAll(async()=>{await db?.close();});beforeEach(async()=>{await db.exec('begin');});afterEach(async()=>{await db.exec('rollback');});
it('closes an actual USD40 service paid with USD40 without overpayment',async()=>{const id=await order();await one('select close_order($1)',[id]);expect(await one('select total_ves::float from orders where id=$1',[id])).toBe(8000);const w=await review();expect(w).toHaveLength(1);expect(Number(w[0].amount)).toBe(16);expect(w[0].currency).toBe('USD');});
it('keeps existing REF pricing and collects the correct USD equivalent',async()=>{const id=await order('REF',20);await one('select close_order($1)',[id]);const w=await review();expect(Number(w[0].amount)).toBe(8);});
it('splits commissions by actual collection currency and never duplicates a review',async()=>{const id=await order('USD',20,4000);await one('select close_order($1)',[id]);await review();const w=await review();expect(w).toHaveLength(2);expect(Number(w.find((w:any)=>w.currency==='USD').amount)).toBe(8);expect(Number(w.find((w:any)=>w.currency==='VES').amount)).toBe(1600);});
it('requires a reason, records before/after and rejects a stale review',async()=>{const id=await order();await one('select close_order($1)',[id]);const [w]=await review();await rejects(()=>one("select payroll_review_work($1,1,'PAY',18,'')",[w.id]),/motivo/);await one("select payroll_review_work($1,1,'PAY',18,'Bono por trabajo adicional')",[w.id]);expect(await one('select count(*)::int from payroll_work_history')).toBe(1);await rejects(()=>one("select payroll_review_work($1,1,'HOLD',18,'Pendiente de revisión')",[w.id]),/cambió/);});
it('snapshots the final amount and never pays it twice',async()=>{const id=await order();await one('select close_order($1)',[id]);const [w]=await review();await one("select payroll_review_work($1,1,'PAY',18,'Bono por trabajo adicional')",[w.id]);const run=await settle();expect(await one('select commission_usd::float from payroll_runs where id=$1',[run])).toBe(18);expect(await review()).toHaveLength(0);await rejects(()=>one("select payroll_review_work($1,2,'PAY',20,'Otro ajuste posterior')",[w.id]),/liquidado/);});
it('does not pay excluded work; held work remains available',async()=>{const id=await order('USD',20,4000);await one('select close_order($1)',[id]);const [a,b]=await review();await one("select payroll_review_work($1,1,'EXCLUDE',$2,'Garantía sin comisión')",[a.id,a.amount]);await one("select payroll_review_work($1,1,'HOLD',$2,'Pagar la semana siguiente')",[b.id,b.amount]);await settle();const pending=await review();expect(pending).toHaveLength(1);expect(pending[0].decision).toBe('HOLD');});
it('reverses a cancelled paid commission in its original currency exactly once',async()=>{const id=await order();await one('select close_order($1)',[id]);await settle();await one("select cancel_order($1,'Prueba de anulación real')",[id]);await review();const w=await review();expect(w).toHaveLength(1);expect(Number(w[0].amount)).toBe(-16);expect(w[0].currency).toBe('USD');expect(await one('select count(*)::int from payroll_adjustments')).toBe(0);});
it('blocks unauthorized payroll review',async()=>{await db.exec("select set_config('request.jwt.claim.sub','10000000-0000-0000-0000-000000000002',true)");await rejects(review,/Solo/);});
it('preserves USD40 across a later exchange-rate change',async()=>{const id=await order('USD',0);await db.exec("insert into exchange_rates(rate_type,value,effective_at) values('OPERATIVE',250,now())");await one("select add_payment($1,'CASH_USD',40)",[id]);await one('select close_order($1)',[id]);expect(Number((await review())[0].amount)).toBe(16);});
it.each(['ZELLE','BINANCE'])('records %s in its own USD account, not the cash drawer',async(method)=>{const id=await order('USD',0);await one('select close_order_with_full_payment($1,$2)',[id,method]);expect(await one('select currency from payments where order_id=$1',[id])).toBe('USD');expect(await one('select a.code from account_movements m join financial_accounts a on a.id=m.account_id')).toBe(method);expect(Number((await review())[0].amount)).toBe(16);});
it('pays only the collected part of credit and adds later collections once',async()=>{const id=await order('USD',20);const customer=await one("insert into customers(name) values('Cliente de prueba') returning id");await db.query('update orders set customer_id=$1 where id=$2',[customer,id]);const vehicle=await one('insert into vehicles(customer_id,plate) values($1,$2) returning id',[customer,'TEST123']);await db.query('update orders set vehicle_id=$1 where id=$2',[vehicle,id]);await one('select close_order_with_credit($1)',[id]);expect(Number((await review())[0].amount)).toBe(8);await settle();const r=await one('select id from receivables where order_id=$1',[id]);await one("select record_credit_payment($1,'CASH_VES',4000)",[r]);const w=await review();expect(w).toHaveLength(1);expect(w[0].currency).toBe('VES');expect(Number(w[0].amount)).toBe(1600);});
it('keeps the fixed salary separate from collection currencies',async()=>{const id=await order();await one('select close_order($1)',[id]);const [w]=await review();await db.query("insert into compensation_rules(employee_id,rule_type,value,valid_from) values($1,'FIXED_WEEKLY',50,current_date-30)",[w.employee_id]);const run=await settle();expect(await one('select fixed_ref::float from payroll_runs where id=$1',[run])).toBe(50);expect(await one('select commission_usd::float from payroll_runs where id=$1',[run])).toBe(16);});
it('rejects a changed summary before settlement',async()=>{const id=await order();await one('select close_order($1)',[id]);const [w]=await review();await rejects(()=>one('select payroll_settle($1,current_date-6,current_date,$2)',[w.employee_id,'[]']),/Cambió/);expect(await one('select count(*)::int from payroll_runs')).toBe(0);});


