"use client";
import Link from "next/link";
import { useParams,useRouter } from "next/navigation";
import { useEffect,useState } from "react";
import { supabase } from "@/lib/supabase";
import { fmtRef,fmtVes } from "@/lib/format";
import { businessInstant,caracasInput,paymentMethods } from "@/lib/order-admin";
type Line={source_id:string;description:string;quantity:number;unit_ref:number;bcv_rate_snapshot:number};
type Pay={source_id:string;method:string;amount_original:number;reference:string;installment:boolean};
export default function CorrectOrder(){
 const {id}=useParams<{id:string}>(),router=useRouter();
 const [order,setOrder]=useState<any>(null),[items,setItems]=useState<Line[]>([]),[payments,setPayments]=useState<Pay[]>([]),[date,setDate]=useState("");
 const [reason,setReason]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[admin,setAdmin]=useState(false),[loading,setLoading]=useState(true),[finance,setFinance]=useState("");
 useEffect(()=>{(async()=>{
  const a=await supabase.rpc("can_administer_orders");if(a.error||a.data!==true){setLoading(false);return setError(a.error?.message||"Solo lubricenterc@gmail.com puede corregir ventas cerradas.");}setAdmin(true);
  const [o,i,p,c,r]=await Promise.all([supabase.from("orders").select("*").eq("id",id).single(),supabase.from("order_items").select("*").eq("order_id",id).order("created_at"),supabase.from("payments").select("*").eq("order_id",id).order("paid_at"),supabase.from("cashea_sales").select("initial_percent").eq("order_id",id).maybeSingle(),supabase.from("receivables").select("id").eq("order_id",id).maybeSingle()]);
  const err=o.error||i.error||p.error||c.error||r.error;setLoading(false);if(err)return setError(err.message);
  if(o.data.status!=="CLOSED")return setError("Esta venta no está cerrada. Vuelve al listado para abrir su versión vigente.");
  const ids=(p.data??[]).map(x=>x.id);const h=ids.length?await supabase.rpc("order_installment_payment_ids",{p_order_id:id}):{data:[],error:null};if(h.error)return setError(h.error.message);
  setOrder(o.data);setDate(caracasInput(o.data.business_at||o.data.closed_at||o.data.opened_at));
  setItems((i.data??[]).map(x=>({...x,source_id:x.id,quantity:Number(x.quantity),unit_ref:Number(x.charged_ref_amount)/Number(x.quantity)})));
  const installments=new Set((h.data??[]) as string[]);setPayments((p.data??[]).map(x=>({...x,source_id:x.id,amount_original:Number(x.amount_original),reference:x.reference||"",installment:installments.has(x.id)})));
  setFinance(c.data?`Cashea: se conserva la inicial del ${c.data.initial_percent}%, la comisión y las cuotas recibidas. Si cambias el total, ajusta los pagos de la inicial.`:r.data?"Crédito LC: se recalculará el saldo con los pagos conservados.":"Contado / mixto: los pagos deben cubrir el total corregido.");
 })();},[id]);
 const total=items.reduce((s,x)=>s+x.quantity*x.unit_ref,0);
 async function save(){if(busy||!order||reason.trim().length<5)return;setBusy(true);setError("");try{const r=await supabase.rpc("correct_closed_order",{p_order_id:id,p_reason:reason.trim(),p_business_at:businessInstant(date),p_items:items,p_payments:payments,p_customer_id:order.customer_id,p_vehicle_id:order.vehicle_id});if(r.error)throw r.error;router.replace(`/orders/${r.data}`);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <main className="container stack"><div className="row-between"><h1>Corregir {order?.order_number||"venta"}</h1><Link className="btn" href={`/orders/${id}`}>Volver</Link></div>{error&&<div className="error" role="alert">{error}</div>}{loading&&<p>Cargando venta…</p>}{admin&&order&&<>
  <section className="card stack"><p>Al guardar se anulará la versión anterior y se creará una venta corregida, cerrada y enlazada al original. Caja, stock y comisiones se ajustan juntos. Si algún dato no cuadra, no se guarda ningún cambio.</p><p className="muted">{finance}</p><label><span className="label">Motivo obligatorio</span><textarea className="input" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explica qué estaba incorrecto y por qué"/></label><label><span className="label">Fecha real de la venta · Venezuela</span><input className="input" type="datetime-local" max={caracasInput()} value={date} onChange={e=>setDate(e.target.value)}/></label></section>
  <section className="card stack"><h2>Productos y trabajos</h2><p className="small muted">Se conservan las tasas de cada línea. Al cambiar precio o cantidad, las comisiones se ajustan proporcionalmente.</p>{items.map((x,index)=><div key={x.source_id} className="order-item stack"><label><span className="label">Descripción</span><input className="input" value={x.description} onChange={e=>setItems(a=>a.map((r,j)=>j===index?{...r,description:e.target.value}:r))}/></label><div className="grid grid-2"><label><span className="label">Cantidad</span><input className="input" type="number" min="0.01" step="0.01" value={x.quantity} onChange={e=>setItems(a=>a.map((r,j)=>j===index?{...r,quantity:Number(e.target.value)}:r))}/></label><label><span className="label">Precio unitario REF</span><input className="input" type="number" min="0" step="0.0001" value={x.unit_ref} onChange={e=>setItems(a=>a.map((r,j)=>j===index?{...r,unit_ref:Number(e.target.value)}:r))}/></label></div><div className="row-between"><span>{fmtRef(x.quantity*x.unit_ref)} · tasa original {fmtVes(x.bcv_rate_snapshot)}</span><button className="btn btn-ghost" onClick={()=>setItems(a=>a.filter((_,j)=>j!==index))}>Quitar línea</button></div></div>)}</section>
  <section className="card stack"><h2>Pagos registrados</h2><p className="muted small">Revisa los importes realmente recibidos. Las cuotas Cashea ya cobradas se conservan.</p>{payments.map((p,index)=><div className="order-item stack" key={p.source_id}><div className="grid grid-2"><label><span className="label">Método {p.installment?"· cuota Cashea":""}</span><select className="select" disabled={p.installment} value={p.method} onChange={e=>setPayments(a=>a.map((r,j)=>j===index?{...r,method:e.target.value}:r))}>{Object.entries(paymentMethods).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label><span className="label">Monto {p.method==='CASH_USD'?'USD':'Bs'}</span><input className="input" disabled={p.installment} type="number" min="0.01" step="0.01" value={p.amount_original} onChange={e=>setPayments(a=>a.map((r,j)=>j===index?{...r,amount_original:Number(e.target.value)}:r))}/></label></div><label><span className="label">Referencia</span><input className="input" value={p.reference} onChange={e=>setPayments(a=>a.map((r,j)=>j===index?{...r,reference:e.target.value}:r))}/></label>{!p.installment&&<button className="btn btn-ghost" onClick={()=>setPayments(a=>a.filter((_,j)=>j!==index))}>Quitar pago incorrecto</button>}</div>)}</section>
  <section className="card stack"><strong>Total corregido: {fmtRef(total)}</strong><button className="btn btn-primary" disabled={busy||!items.length||reason.trim().length<5||!date} onClick={save}>{busy?"Guardando corrección…":"Guardar corrección y cerrar venta"}</button></section>
 </>}</main>;
}

