'use client';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
const states={READY:'Para hacer ahora',NEEDS_INFO:'Por aclarar',WAITING:'Esperando',RESOLVED:'Resueltas / excluidas'};
type State=keyof typeof states;
type Task={id:string;title:string;explanation:string;kind:string;subject_id:string;subject_type:string;status:string;work_status:State;work_version:number;work_note:string|null;review_on:string|null;responsible:string|null;responsible_email:string|null;priority:number;evidence:Record<string,unknown>};
type Tasks={total:number;counts:Partial<Record<State,number>>;rows:Task[];assignees:{id:string;email:string}[]};
export function FinanceTaskList({onOpen,revision}:{onOpen:(task:Task)=>void;revision:unknown}){
 const [state,setState]=useState<State>('READY'),[offset,setOffset]=useState(0),[data,setData]=useState<Tasks|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [history,setHistory]=useState<{id:string;created_at:string;actor_id:string;data:{before?:Task;after?:Task}}[]|null>(null);
 async function showHistory(id:string){const r=await supabase.from('audit_events').select('id,created_at,actor_id,data').eq('entity_type','reconciliation_cases').eq('entity_id',id).order('created_at',{ascending:false}).limit(20);if(r.error)setError(r.error.message);else setHistory(r.data??[]);}
 const [edit,setEdit]=useState<Task|null>(null),[status,setStatus]=useState<State>('READY'),[assignee,setAssignee]=useState(''),[date,setDate]=useState(''),[note,setNote]=useState('');
 async function load(){const r=await supabase.rpc('finance_tasks',{p_state:state,p_offset:offset});if(r.error)throw r.error;setData(r.data);}
 useEffect(()=>{setError('');void load().catch(e=>setError(e.message));},[state,offset,revision]);
 async function save(){if(!edit||busy)return;setBusy(true);setError('');try{const r=await supabase.rpc('finance_followup',{p_id:edit.id,p_version:edit.work_version,p_status:status,p_assignee:assignee||null,p_review_on:date||null,p_note:note});if(r.error)throw r.error;setEdit(null);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="card stack"><h2>Mis pendientes financieros</h2><p className="muted">Organiza las aclaraciones sin alterar el dinero. Al llegar la fecha de revisión, el pendiente vuelve a «Para hacer ahora».</p>
 <div className="row" style={{flexWrap:'wrap'}}>{Object.entries(states).map(([key,label])=><button key={key} className={state===key?'btn btn-primary':'btn'} disabled={busy} aria-pressed={state===key} onClick={()=>{setState(key as State);setOffset(0);}}>{label} ({data?.counts[key as State]??0})</button>)}<button className="btn" disabled={busy} onClick={()=>{void load().catch(e=>setError(e.message));}}>Actualizar</button></div>
 {error&&<div className="error" role="alert">{error}</div>}
 {data?.rows.map(t=><article className="card stack" key={t.id}><strong>{t.title}</strong><p>{t.explanation}</p><div className="muted small">Responsable: {t.responsible_email??'Pendiente de asignación'}{t.review_on?` · Revisar: ${t.review_on}`:''} · {t.priority===1?'La contradicción impide verificar':t.priority===2?'Verificar reporte o caja':'Aclarar el movimiento'}</div>{t.work_note&&<p>Siguiente paso: {t.work_note}</p>}{t.status!=='OPEN'&&<p>{t.status==='DISMISSED'?'Excluida; no equivale a dinero conciliado.':'Resuelta según su evidencia.'}</p>}<div className="row" style={{flexWrap:'wrap'}}><button className="btn" disabled={busy} onClick={()=>onOpen(t)}>Ver evidencia / resolver</button><button className="btn" disabled={busy} onClick={()=>showHistory(t.id)}>Historial</button>{t.status==='OPEN'&&<button className="btn" disabled={busy} onClick={()=>{setEdit(t);setStatus(t.work_status);setAssignee(t.responsible??'');setDate(t.review_on??'');setNote(t.work_note??'');}}>No sé todavía / organizar</button>}</div></article>)}
 {data&&!data.rows.length&&<p>No hay tareas en este filtro. Consulta también la cobertura: esto no certifica que el mes esté conciliado.</p>}
 {data&&<div className="row"><button className="btn" disabled={busy||offset===0} onClick={()=>setOffset(Math.max(0,offset-20))}>Anterior</button><span>{data.total} tareas</span><button className="btn" disabled={busy||offset+20>=data.total} onClick={()=>setOffset(offset+20)}>Siguiente</button></div>}
 {history&&<div className="overlay"><section className="sheet stack" role="dialog" aria-modal="true" aria-label="Historial del pendiente"><h2>Últimas 20 decisiones</h2>{history.map(h=><article className="card stack" key={h.id}><div>{new Date(h.created_at).toLocaleString('es-VE',{timeZone:'America/Caracas'})} · {data?.assignees.find(a=>a.id===h.actor_id)?.email??'Sistema / usuario anterior'}</div><div>{h.data.before?.work_status??'Creado'} → {h.data.after?.work_status??'Estado anterior'} · {h.data.after?.status}</div>{h.data.after?.work_note&&<p>{h.data.after.work_note}</p>}</article>)}{!history.length&&<p>Sin decisiones registradas.</p>}<button className="btn" onClick={()=>setHistory(null)}>Cerrar</button></section></div>}
 {edit&&<div className="overlay"><section className="sheet stack" role="dialog" aria-modal="true" aria-label="Organizar pendiente"><h2>{edit.title}</h2><label>Estado<select className="select" value={status} onChange={e=>setStatus(e.target.value as State)}>{Object.entries(states).filter(([s])=>s!=='RESOLVED').map(([s,label])=><option key={s} value={s}>{label}</option>)}</select></label><label>Responsable<select className="select" value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Responsable predeterminado</option>{data?.assignees.map(a=><option key={a.id} value={a.id}>{a.email}</option>)}</select></label><label>Volver a revisar<input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Qué falta y siguiente paso<textarea className="input" value={note} onChange={e=>setNote(e.target.value)}/></label>{error&&<div className="error" role="alert">{error}</div>}<button className="btn btn-primary" disabled={busy||note.trim().length<5||(status!=='READY'&&!date)} onClick={save}>Guardar seguimiento</button><button className="btn" disabled={busy} onClick={()=>setEdit(null)}>Volver</button></section></div>}
 </section>;
}
