'use client';
import { useEffect,useRef,useState } from 'react';
import Link from 'next/link';
import { supabase } from '@/lib/supabase';
type Tender={id:string;order_id:string;customer_label:string;currency:string;received:string;applied:string;change_usd:string;returned_usd:string;change_rate:string};
export function OrderChangePanel({orderId}:{orderId?:string}){
 const [rows,setRows]=useState<Tender[]>([]),[selected,setSelected]=useState<Tender|null>(null),[currency,setCurrency]=useState('USD'),[amount,setAmount]=useState(''),[rate,setRate]=useState(''),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[offset,setOffset]=useState(0),[count,setCount]=useState(0),[confirmed,setConfirmed]=useState(false);
 const request=useRef<string|null>(null);
 const [pending,setPending]=useState(0);
 async function load(){const r=await supabase.rpc('order_change_history',{p_order:orderId||null,p_offset:offset});if(r.error)throw r.error;setRows(r.data.rows??[]);setCount(r.data.total??0);setPending(Number(r.data.pending_usd));}
 useEffect(()=>{load().catch(e=>setError(e.message));},[orderId,offset]);
 async function pay(){if(!selected||busy||!confirmed)return;setBusy(true);setError('');request.current??=crypto.randomUUID();try{const r=await supabase.rpc('return_order_change',{p_request:request.current,p_tender:selected.id,p_usd:amount,p_currency:currency,p_rate:rate,p_note:note});if(r.error)throw r.error;request.current=null;setSelected(null);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const reset=()=>{request.current=null;setConfirmed(false);};
 if(!rows.length&&!error)return null;
 return <section className="card stack"><h2>Vuelto y dinero recibido</h2><strong>Pendiente total por devolver: ${pending.toFixed(2)} USD</strong>{error&&<div className="error">{error}</div>}{rows.map(t=>{const pending=Number(t.change_usd)-Number(t.returned_usd);return <article key={t.id} className="order-item"><div className="row-between"><div><strong>{t.customer_label}</strong><div className="muted small">Recibido {t.received} {t.currency} · aplicado {t.applied} {t.currency}</div><div>Vuelto ${Number(t.change_usd).toFixed(2)} · entregado ${Number(t.returned_usd).toFixed(2)} · pendiente ${pending.toFixed(2)}</div></div>{pending>0&&<button className="btn" disabled={busy} onClick={()=>{setSelected(t);setAmount(pending.toFixed(2));setRate(String(t.change_rate));setNote('');reset();}}>Entregar vuelto</button>}</div>{!orderId&&<Link href={`/orders/${t.order_id}`}>Ver venta</Link>}</article>;})}{count>20&&<div className="row"><button className="btn" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-20))}>Anterior</button><span>{offset+1}–{Math.min(count,offset+20)} de {count}</span><button className="btn" disabled={offset+20>=count} onClick={()=>setOffset(offset+20)}>Siguiente</button></div>}
 {selected&&<div className="overlay"><div className="sheet stack" role="dialog" aria-modal="true" aria-label="Entregar vuelto pendiente"><h2>Entregar vuelto pendiente</h2><fieldset disabled={busy} className="stack" style={{border:0,padding:0}}><label>USD que devuelves<input className="input" inputMode="decimal" value={amount} onChange={e=>{setAmount(e.target.value);reset();}}/></label><label>Moneda<select className="select" value={currency} onChange={e=>{setCurrency(e.target.value);reset();}}><option value="USD">Dólares físicos</option><option value="VES">Bolívares físicos</option></select></label><label>Tasa acordada · Bs/USD<input className="input" inputMode="decimal" value={rate} onChange={e=>{setRate(e.target.value);reset();}}/></label>{currency==='VES'&&<p>Sale de Caja Bs: {(Number(amount)*Number(rate)).toFixed(2)} Bs</p>}<label>Nota de la entrega<input className="input" value={note} onChange={e=>{setNote(e.target.value);reset();}}/></label><label className="row"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Ya entregué este dinero al cliente.</label></fieldset><button className="btn btn-primary" disabled={busy||!confirmed} onClick={pay}>Registrar entrega</button><button className="btn" disabled={busy} onClick={()=>setSelected(null)}>Cancelar</button></div></div>}
 </section>;
}
