"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabase";
import {fmtRef,fmtVes} from "@/lib/format";
type Work={id:string;employee_id:string;order_id:string;order_number:string;description:string;currency:string;original_amount:number;amount:number;decision:string;reason:string|null;version:number;earned_at:string;reversal_of:string|null};
type OrderTotal={id:string;total_ves:number;total_ref:number;total_cash_usd_equivalent:number};
function money(n:number,c:string){return c==='USD'?`$${Number(n).toFixed(2)} USD`:fmtVes(n);}
function start(end:string){const d=new Date(end+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-6);return d.toISOString().slice(0,10);}
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Caracas'}).format(new Date());}
function grouped(rows:Work[]){return Object.values(rows.reduce<Record<string,{id:string;number:string;rows:Work[]}>>((groups,w)=>{(groups[w.order_id]??={id:w.order_id,number:w.order_number,rows:[]}).rows.push(w);return groups;},{}));}
export default function PayrollReview(){
 const [end,setEnd]=useState(today);
 const [paymentDate,setPaymentDate]=useState(today);
 const [bcv,setBcv]=useState<{value:number;effective_at:string}|null>(null);
 const [orders,setOrders]=useState<Record<string,OrderTotal>>({});
 const [work,setWork]=useState<Work[]>([]),[employees,setEmployees]=useState<any[]>([]),[rules,setRules]=useState<any[]>([]),[adjustments,setAdjustments]=useState<any[]>([]),[runs,setRuns]=useState<any[]>([]);
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[latest,setLatest]=useState('');
 const [edit,setEdit]=useState<Work|null>(null),[decision,setDecision]=useState('PAY'),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[confirm,setConfirm]=useState<any>(null),[history,setHistory]=useState<any[]|null>(null);
 const [adjEmployee,setAdjEmployee]=useState(''),[adjAmount,setAdjAmount]=useState(''),[adjReason,setAdjReason]=useState('');
 async function load(){setReady(false);setError('');const [w,e,r,a,c]=await Promise.all([supabase.rpc('payroll_review',{p_end:end}),supabase.from('employees').select('id,name').eq('active',true).order('name'),supabase.from('payroll_runs').select('*,employees(name)').order('created_at',{ascending:false}).limit(20),supabase.from('payroll_adjustments').select('*').is('payroll_run_id',null).lte('occurred_on',end),supabase.from('compensation_rules').select('*').eq('rule_type','FIXED_WEEKLY').lte('valid_from',end).order('valid_from',{ascending:false})]);const bad=[w,e,r,a,c].find(x=>x.error);if(bad?.error)return setError(bad.error.message);const ids=[...new Set((w.data??[]).map((row:Work)=>row.order_id))];if(ids.length){const result=await supabase.from('orders').select('id,total_ves,total_ref,total_cash_usd_equivalent').in('id',ids);if(result.error)return setError(result.error.message);setOrders(Object.fromEntries((result.data??[]).map(row=>[row.id,row])));}else setOrders({});setWork(w.data??[]);setEmployees(e.data??[]);setRuns(r.data??[]);setAdjustments(a.data??[]);setRules(c.data??[]);setReady(true);}
 useEffect(()=>{void load();},[end]);
 useEffect(()=>{let active=true;setBcv(null);void supabase.from('exchange_rates').select('value,effective_at').eq('rate_type','BCV').lte('effective_at',`${paymentDate}T23:59:59-04:00`).order('effective_at',{ascending:false}).limit(1).then(({data})=>{if(active&&data?.[0])setBcv({value:Number(data[0].value),effective_at:data[0].effective_at});});return()=>{active=false;};},[paymentDate]);
 function summary(id:string){const rows=work.filter(w=>w.employee_id===id),pay=rows.filter(w=>w.decision==='PAY');return{rows,usd:pay.filter(w=>w.currency==='USD').reduce((s,w)=>s+Number(w.amount),0),ves:pay.filter(w=>w.currency==='VES').reduce((s,w)=>s+Number(w.amount),0),hold:rows.filter(w=>w.decision==='HOLD').length,exclude:rows.filter(w=>w.decision==='EXCLUDE').length,fixed:Number(rules.find(r=>r.employee_id===id&&(!r.valid_to||r.valid_to>=end))?.value??0),adj:adjustments.filter(a=>a.employee_id===id).reduce((s,a)=>s+Number(a.amount_ref),0)};}
 async function save(){if(!edit)return;setBusy(true);const {error}=await supabase.rpc('payroll_review_work',{p_id:edit.id,p_version:edit.version,p_decision:decision,p_amount:Number(amount),p_reason:reason});setBusy(false);if(error)return setError(error.message);setEdit(null);await load();}
 async function settle(){setBusy(true);const expected=summary(confirm.id).rows.filter(w=>w.decision!=='HOLD').sort((a,b)=>a.id.localeCompare(b.id)).map(w=>({id:w.id,version:w.version}));const{data,error}=await supabase.rpc('payroll_settle',{p_employee_id:confirm.id,p_period_start:start(end),p_period_end:end,p_expected:{work:expected,fixed_ref:summary(confirm.id).fixed,adjustments:adjustments.filter(a=>a.employee_id===confirm.id).sort((a,b)=>a.id.localeCompare(b.id)).map(a=>({id:a.id,amount_ref:Number(a.amount_ref)}))}});setBusy(false);setConfirm(null);if(error)return setError(error.message);setLatest(data);await load();}
 async function showHistory(id:string){const{data,error}=await supabase.from('payroll_work_history').select('*').eq('work_item_id',id).order('occurred_at',{ascending:false});if(error)return setError(error.message);setHistory(data??[]);}
 async function adjustment(){setBusy(true);const{error}=await supabase.rpc('add_payroll_adjustment',{p_employee_id:adjEmployee,p_adjustment_type:'OTHER',p_amount_ref:Number(adjAmount),p_note:adjReason,p_occurred_on:end});setBusy(false);if(error)return setError(error.message);setAdjAmount('');setAdjReason('');await load();}
 return <main className="container stack"><h1>Nómina · revisión de trabajos</h1><p className="muted">Comisiones según lo cobrado, separadas por moneda. Incluye trabajos pendientes de semanas anteriores. El sueldo fijo sigue separado.</p>
 <div className="row" style={{flexWrap:'wrap'}}><label><span className="label">Cierre de semana</span><input className="input" type="date" value={end} disabled={busy} onChange={e=>{if(e.target.value)setEnd(e.target.value);}}/><span className="muted small">Sueldo fijo: {start(end)} al {end}. Comisiones y ajustes pendientes hasta esta fecha.</span></label><label><span className="label">Fecha prevista de pago</span><input className="input" type="date" max={today()} value={paymentDate} onChange={e=>setPaymentDate(e.target.value)}/><span className="muted small">Solo para estimar bolívares. La tasa real se guarda al registrar el pago.</span></label></div>
 <p className="muted small">{bcv?`Tasa BCV de referencia: ${fmtVes(bcv.value)} por $1 · publicada ${new Date(bcv.effective_at).toLocaleDateString('es-VE',{timeZone:'America/Caracas'})}`:'Sin tasa BCV disponible para esa fecha.'}</p>
 {error&&<div className="error" role="alert">{error}</div>}{latest&&<div className="success">Liquidación guardada. <Link href={`/payroll/${latest}/receipt`}>Ver y registrar pago del sueldo</Link></div>}{!ready&&!error&&<p>Cargando trabajos…</p>}
 {ready&&employees.map(emp=>{const s=summary(emp.id);return <section className="card stack" key={emp.id}>
 <h2>{emp.name}</h2><strong>Comisiones: {money(s.usd,'USD')} · {fmtVes(s.ves)}</strong>
 <div>Sueldo fijo: {fmtRef(s.fixed)} de referencia {bcv&&s.fixed>0?`≈ ${fmtVes(s.fixed*bcv.value)} si se paga el ${paymentDate}`:''}</div>
 <div>Ajustes separados: {fmtRef(s.adj)} de referencia</div>
 <div className="muted small">{s.hold} pendientes · {s.exclude} excluidos. Toca el detalle para ver cada orden y ajustar trabajos.</div>
 <details><summary>Ver trabajos y órdenes ({s.rows.length})</summary><div className="stack" style={{marginTop:12}}>
 {grouped(s.rows).map(group=>{const total=orders[group.id];return <article className="card stack" key={group.id}>
 <div><Link href={`/orders/${group.id}`}><strong>{group.number}</strong></Link></div>
 {total&&<div>Total de la orden: <strong>{fmtVes(total.total_ves)}</strong> · {fmtRef(total.total_ref)} de referencia{Number(total.total_cash_usd_equivalent)>0?` · ${fmtRef(total.total_cash_usd_equivalent)} pactados en divisas`:''}</div>}
 {group.rows.map(w=><div className="stack" key={w.id} style={{borderTop:'1px solid var(--border, #ddd)',paddingTop:8}}>
 <div><strong>{w.description}</strong> · {new Date(w.earned_at).toLocaleDateString('es-VE',{timeZone:'America/Caracas'})} · {{PAY:'Pagar',HOLD:'Pendiente',EXCLUDE:'Excluido'}[w.decision]}</div>
 <div>Le corresponde: <strong>{w.decision==='PAY'?money(w.amount,w.currency):'No se paga'}</strong>{w.decision==='PAY'&&bcv&&<span className="muted small"> · equivalente {w.currency==='USD'?fmtVes(w.amount*bcv.value):fmtRef(w.amount/bcv.value)} a BCV del {paymentDate}</span>}</div>
 <div className="muted small">Calculado inicialmente: {money(w.original_amount,w.currency)}{w.reason?` · Motivo: ${w.reason}`:''}</div>
 <div className="row" style={{flexWrap:'wrap'}}><button className="btn" disabled={busy} onClick={()=>{setEdit(w);setDecision(w.decision);setAmount(String(w.amount));setReason('');setError('');}}>Revisar / ajustar</button><button className="btn btn-ghost" onClick={()=>showHistory(w.id)}>Historial</button></div>
 </div>)}
 </article>;})}
 {!s.rows.length&&<p>Sin comisiones cobradas pendientes.</p>}
 {adjustments.filter(a=>a.employee_id===emp.id).map(a=><div key={a.id}>Ajuste: {fmtRef(a.amount_ref)} de referencia · {a.note}</div>)}
 </div></details>
 <button className="btn btn-primary" disabled={busy||(!s.rows.some(w=>w.decision!=="HOLD")&&!s.fixed&&!s.adj)} onClick={()=>setConfirm(emp)}>Revisar resumen y liquidar</button>
 </section>;})}
 <section className="card stack"><h2>Ajuste separado del sueldo</h2><p className="muted">Positivo: bono. Negativo: deducción. Denominado en REF; no cambia la moneda de las comisiones.</p><select className="select" aria-label="Empleado del ajuste" value={adjEmployee} onChange={e=>setAdjEmployee(e.target.value)}><option value="">Selecciona empleado</option>{employees.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select><input className="input" aria-label="Monto REF" type="number" step="0.01" value={adjAmount} onChange={e=>setAdjAmount(e.target.value)} placeholder="Monto REF con signo"/><textarea className="input" aria-label="Motivo del ajuste" value={adjReason} onChange={e=>setAdjReason(e.target.value)} placeholder="Motivo obligatorio"/><button className="btn" disabled={!ready||busy||!adjEmployee||!Number(adjAmount)||adjReason.trim().length<5} onClick={adjustment}>Guardar ajuste</button></section>
 <section className="card stack"><h2>Últimas liquidaciones</h2>{runs.map(r=><div key={r.id}>{r.employees?.name} · {r.period_start.slice(0,10)} — {r.period_end.slice(0,10)} · <Link href={`/payroll/${r.id}/receipt`}>Ver recibo</Link></div>)}</section>
 {edit&&<div className="overlay"><section className="sheet stack" role="dialog" aria-modal="true" aria-label="Revisar trabajo"><h2>{edit.description}</h2><div>Original: {money(edit.original_amount,edit.currency)}</div><label><span className="label">Decisión</span><select className="select" value={decision} onChange={e=>setDecision(e.target.value)}><option value="PAY">Pagar</option><option value="HOLD">Dejar pendiente</option><option value="EXCLUDE">Excluir del pago</option></select></label><label><span className="label">Monto {edit.currency}</span><input className="input" type="number" step="0.01" value={amount} disabled={!!edit.reversal_of} onChange={e=>setAmount(e.target.value)}/></label><label><span className="label">Motivo obligatorio</span><textarea className="input" value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<div className="error">{error}</div>}<button className="btn btn-primary" disabled={busy||reason.trim().length<5||amount===''||!Number.isFinite(Number(amount))} onClick={save}>Guardar con historial</button><button className="btn" disabled={busy} onClick={()=>setEdit(null)}>Cancelar</button></section></div>}
 {confirm&&<div className="overlay"><section className="sheet stack" role="dialog" aria-modal="true" aria-label="Resumen de nómina"><h2>{confirm.name} · resumen</h2><strong>Comisiones: {money(summary(confirm.id).usd,'USD')} · {fmtVes(summary(confirm.id).ves)}</strong><div>Sueldo fijo: {fmtRef(summary(confirm.id).fixed)} REF</div><div>Ajustes: {fmtRef(summary(confirm.id).adj)} REF</div><p>{summary(confirm.id).hold} trabajos quedan pendientes. {summary(confirm.id).exclude} se excluyen sin pagarlos.</p><button className="btn btn-primary" disabled={busy} onClick={settle}>Confirmar liquidación</button><button className="btn" disabled={busy} onClick={()=>setConfirm(null)}>Volver a revisar</button></section></div>}
 {history&&<div className="overlay"><section className="sheet stack" role="dialog" aria-modal="true" aria-label="Historial"><h2>Historial</h2>{!history.length&&<p>Sin ajustes manuales.</p>}{history.map(h=><div className="card" key={h.id}><strong>{h.reason}</strong><div>{h.before_data.decision} → {h.after_data.decision} · {money(h.before_data.amount,h.before_data.currency)} → {money(h.after_data.amount,h.after_data.currency)}</div><div className="muted small">{new Date(h.occurred_at).toLocaleString('es-VE')} · Usuario {h.actor_id}</div></div>)}<button className="btn" onClick={()=>setHistory(null)}>Cerrar</button></section></div>}
 </main>;
}
