'use client';
import {useRef,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {TenderFields,type TenderDraft} from './tender-fields';
export function QuickTenderCheckout({items,method,reference,totalVes,totalRef,rate,bcv,businessAt,onDone,onCancel}:{items:unknown;method:string;reference:string;totalVes:number;totalRef:number;rate:number;bcv:number;businessAt:string|null;onDone:(sale:any)=>Promise<void>;onCancel:()=>void}){
 const cash=method==='CASH_USD'||method==='CASH_VES';
 const currency=['CASH_USD','ZELLE','BINANCE'].includes(method)?'USD':'VES';
 const [agreed,setAgreed]=useState(false),[price,setPrice]=useState(totalRef.toFixed(2)),[draft,setDraft]=useState<TenderDraft>({received:method.startsWith('CASH')?'':(currency==='USD'?totalVes/rate:totalVes).toFixed(2),returnUsd:'0',returnCurrency:'USD',changeRate:String(bcv),customerLabel:'',confirmed:false}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const request=useRef<string|null>(null);
 const payable=agreed?Number(price)*rate:totalVes;
 function update(v:TenderDraft){setDraft(v);request.current=null;}
 function setAgreement(value:boolean,amount:string){setAgreed(value);setPrice(amount);request.current=null;setDraft(d=>({...d,confirmed:false}));}
 async function collect(){if(busy||(cash&&!draft.confirmed))return;setBusy(true);setError('');request.current??=crypto.randomUUID();try{const r=await supabase.rpc('quick_sale_with_tender',{p_request:request.current,p_items:items,p_method:method,p_received:draft.received,p_return_usd:draft.returnUsd||'0',p_return_currency:draft.returnCurrency,p_change_rate:draft.changeRate,p_reference:reference.trim()||null,p_customer_label:draft.customerLabel.trim()||null,p_business_at:businessAt,p_agreed_usd:agreed?price:null});if(r.error)throw r.error;request.current=null;await onDone(r.data);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="overlay"><div className="sheet stack" role="dialog" aria-modal="true" aria-label="Cobro de venta rápida"><h2>{cash?'Cobrar venta y registrar vuelto':'Cobrar venta'}</h2><fieldset className="stack" disabled={busy} style={{border:0,padding:0}}>{currency==='USD'&&<label className="row"><input type="checkbox" checked={agreed} onChange={e=>setAgreement(e.target.checked,price)}/>Precio final / rebaja acordada en USD.</label>}{agreed&&<label>Total pactado USD<input className="input" inputMode="decimal" value={price} onChange={e=>setAgreement(true,e.target.value)}/></label>}<div className="muted small">{agreed?'El precio en dólares se conserva. El total acordado se distribuye proporcionalmente entre los productos.':'Se conserva la cotización actual de los productos y su tasa de cobro.'}</div><TenderFields cash={cash} value={draft} onChange={update} currency={currency} remainingVes={payable} paymentRate={rate} fixedUsd={agreed?Number(price):undefined}/></fieldset>{error&&<div className="error">{error}</div>}<button className="btn btn-primary" disabled={busy||(cash&&!draft.confirmed)||!Number.isFinite(Number(draft.received))||Number(draft.received)<=0||!Number.isFinite(payable)||payable<=0} onClick={collect}>{busy?'Registrando…':'Cobrar y cerrar venta'}</button><button className="btn" disabled={busy} onClick={onCancel}>Cancelar</button></div></div>;
}
