'use client';
import { changeQuote } from '@/lib/finance/change';
import { D } from '@/lib/finance/money';
export type TenderDraft = {received:string;returnUsd:string;returnCurrency:string;changeRate:string;customerLabel:string;confirmed:boolean};
export function TenderFields({value,onChange,currency,remainingVes,paymentRate,fixedUsd,cash=true}:{value:TenderDraft;onChange:(v:TenderDraft)=>void;currency:string;remainingVes:number;paymentRate:number;fixedUsd?:number;cash?:boolean}) {
 const update=(patch:Partial<TenderDraft>)=>onChange({...value,...patch,confirmed:false});
 let quote:ReturnType<typeof changeQuote>|null=null,error='';
 let due:string|null=null;
 try{due=changeQuote(remainingVes,'0.01',currency,paymentRate,value.changeRate,fixedUsd).due;}catch{}
 try{quote=changeQuote(remainingVes,value.received,currency,paymentRate,value.changeRate,fixedUsd);}catch(e){if(value.received)error=(e as Error).message;}
 const usd=Number(quote?.changeUsd||0), returned=Number(value.returnUsd||0);
 const pending=usd-returned;
 if(!cash)return <div className="stack">{due&&<strong>Total por cobrar: {due} {currency}</strong>}<label>Monto del pago · {currency}<input className="input" inputMode="decimal" value={value.received} onChange={e=>update({received:e.target.value})}/></label>{fixedUsd!==undefined&&currency==='VES'&&<label>Tasa BCV · Bs por USD<input className="input" inputMode="decimal" value={value.changeRate} readOnly/></label>}{due&&<button type="button" className="btn" onClick={()=>update({received:due!,returnUsd:'0'})}>Usar monto exacto · {due} {currency}</button>}{usd>0&&<p className="error" role="alert">El monto supera el saldo de la venta. Corrige el pago o el precio acordado antes de registrarlo.</p>}{error&&<p className="error" role="alert">{error}</p>}</div>;
 return <div className="card stack"><label>Recibido realmente · {currency}<input className="input" inputMode="decimal" value={value.received} onChange={e=>update({received:e.target.value})}/></label>
 <div className="row">{(currency==='USD'?[1,2,5,10,20,50,100]:[5,10,20,50,100,200,500]).map(b=><button type="button" className="btn btn-ghost" key={b} onClick={()=>update({received:new D(Number.isFinite(Number(value.received))?value.received||0:0).add(b).toFixed(2)})}>+ {currency==='USD'?'$':'Bs '}{b}</button>)}<button type="button" className="btn btn-ghost" onClick={()=>update({received:'',returnUsd:'0'})}>Limpiar billetes</button></div>
 <label>{currency==='VES'?'Tasa BCV · Bs por USD':'Tasa para entregar vuelto en Bs'}<input className="input" inputMode="decimal" value={value.changeRate} readOnly={currency==='VES'} onChange={e=>update({changeRate:e.target.value})}/></label><div className="muted small">{fixedUsd!==undefined?'Conserva el precio USD. Convierte el cobro en Bs y el vuelto en Bs a esta tasa.':'Convierte el vuelto; conserva la cotización y la tasa de cobro de la orden.'}</div>
 {due&&<button type="button" className="btn" onClick={()=>update({received:due!})}>Cobrar exacto · {due} {currency}</button>}
 {quote&&<><div className="row-between"><span>Aplicado a la venta · {currency}</span><strong>{quote.applied}</strong></div><div className="row-between"><span>Vuelto total USD</span><strong>${quote.changeUsd}</strong></div>{usd>0&&<><label>USD de vuelto que entregas ahora<input className="input" inputMode="decimal" value={value.returnUsd} onChange={e=>update({returnUsd:e.target.value})}/></label><button type="button" className="btn" onClick={()=>update({returnUsd:quote!.changeUsd})}>Entregar todo el vuelto</button><label>Moneda que entregas<select className="select" value={value.returnCurrency} onChange={e=>update({returnCurrency:e.target.value})}><option value="USD">Dólares físicos</option><option value="VES">Bolívares físicos</option></select></label>{value.returnCurrency==='VES'&&<strong>Sale de Caja Bs: {new D(returned||0).mul(value.changeRate||1).toFixed(2)} Bs</strong>}<div className={pending<0?'error':'muted'}>Pendiente de devolver: ${pending.toFixed(2)} USD</div>{pending>0&&<label>Cliente del vuelto pendiente · nombre o teléfono<input className="input" value={value.customerLabel} onChange={e=>update({customerLabel:e.target.value})}/></label>}</>}
 {Number(quote.roundingVes)!==0&&<p>Ajuste por redondear el vuelto a centavos USD: {quote.roundingVes} Bs. Confirma este ajuste con el cliente.</p>}
 <label className="row"><input type="checkbox" checked={value.confirmed} onChange={e=>onChange({...value,confirmed:e.target.checked})}/>Confirmo el dinero recibido, el vuelto entregado y el cálculo acordado.</label></>}
 {error&&<div className="error" role="alert">{error}</div>}</div>;
}
