"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { fmtDate, fmtRef, fmtVes } from "@/lib/format";
type Sale = {id:string;order_number:string;status:string;sale_at:string;customer_id:string|null;customer_name:string|null;plate:string|null;kind:string;total_ref:number;total_ves:number;payment_type:string;has_financed_sale:boolean;cancellation_reason:string|null};
export default function OrdersPage() {
 const [rows,setRows]=useState<Sale[]>([]),[count,setCount]=useState(0),[page,setPage]=useState(0);
 const [query,setQuery]=useState(""),[status,setStatus]=useState("ALL"),[from,setFrom]=useState(""),[to,setTo]=useState("");
 const [admin,setAdmin]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[revision,setRevision]=useState(0);
 const [cancel,setCancel]=useState<Sale|null>(null),[reason,setReason]=useState(""),[keepAsBalance,setKeepAsBalance]=useState(false);
 useEffect(()=>{supabase.rpc("can_administer_orders").then(({data})=>setAdmin(data===true));},[]);
 useEffect(()=>{let active=true;setLoading(true);const timer=setTimeout(async()=>{
  const r=await supabase.rpc("search_order_admin",{p_query:query,p_status:status,p_from:from||null,p_to:to||null,p_page:page});
  if(!active)return;setLoading(false);if(r.error){setRows([]);return setError(r.error.message);}setRows(r.data?.rows??[]);setCount(Number(r.data?.count??0));setError("");
 },250);return()=>{active=false;clearTimeout(timer);};},[query,status,from,to,page,revision]);
 async function annul(){if(!cancel||busy||reason.trim().length<5)return;setBusy(true);setError("");const r=await supabase.rpc(keepAsBalance?"cancel_order_to_customer_balance":"cancel_order",{p_order_id:cancel.id,p_reason:reason.trim()});setBusy(false);if(r.error)return setError(r.error.message);setCancel(null);setReason("");setKeepAsBalance(false);setRevision(x=>x+1);}
 return <main className="container stack">
  <div className="row-between"><div><h1>Ventas y órdenes</h1><p className="muted">Órdenes y ventas reales. Los mantenimientos antiguos se consultan por separado, sin sumarlos a la facturación.</p></div><div className="row" style={{flexWrap:"wrap"}}><Link className="btn" href="/service-history">Historial de mantenimiento</Link><Link className="btn" href="/quick-sale">Venta rápida</Link><Link className="btn btn-primary" href="/orders/new">+ Orden completa</Link></div></div>
  {error&&<div className="error" role="alert">{error}</div>}
  <section className="card stack"><label><span className="label">Buscar en todas las ventas</span><input className="input" placeholder="N° de orden, cliente, teléfono o placa" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><div className="grid grid-3"><label><span className="label">Estado</span><select className="select" value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="ALL">Todas</option><option value="OPEN">Abiertas</option><option value="CLOSED">Cerradas</option><option value="CANCELLED">Anuladas</option></select></label><label><span className="label">Desde</span><input className="input" type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(0);}}/></label><label><span className="label">Hasta</span><input className="input" type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(0);}}/></label></div></section>
  {cancel&&<section className="card stack" role="region" aria-label="Anular venta"><h2>Anular {cancel.order_number}</h2><p>El stock y las comisiones se revertirán. El original y el motivo seguirán visibles en el historial.</p>{cancel.status==='CLOSED'&&<div className="stack"><strong>¿Qué pasó con el dinero recibido?</strong><label className="row"><input type="radio" checked={!keepAsBalance} onChange={()=>setKeepAsBalance(false)}/><span>Se devolvió al cliente lo cobrado por la venta · registrar salida de caja</span></label>{cancel.customer_id&&!cancel.has_financed_sale?<label className="row"><input type="radio" checked={keepAsBalance} onChange={()=>setKeepAsBalance(true)}/><span>El cliente lo conserva como saldo a favor · no salió dinero de caja</span></label>:<div className="muted small">Para conservar el cobro como saldo, la venta debe tener cliente y no incluir Cashea ni Crédito LC.</div>}</div>}{keepAsBalance?<div className="card muted small">Los cobros en Bs se acreditarán con su BCV original; los cobros en USD quedarán en divisas. El saldo aparecerá en la ficha del cliente.</div>:<div className="muted small">Si un pago tuvo sobrante separado como saldo a favor, ese sobrante permanece. Devuélvelo aparte desde la ficha del cliente si también entregaste ese dinero.</div>}<label><span className="label">Motivo obligatorio</span><textarea className="input" autoFocus value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ej. el cliente no compró; se cerró al preparar el recibo"/></label><div className="row"><button className="btn" disabled={busy} onClick={()=>setCancel(null)}>Volver</button><button className="btn btn-primary" disabled={busy||reason.trim().length<5} onClick={annul}>{busy?"Anulando…":keepAsBalance?"Anular y acreditar saldo":"Confirmar anulación y reversión"}</button></div></section>}
  <section className="card" style={{overflowX:"auto"}} aria-busy={loading}><table className="table sales-table"><caption style={{textAlign:"left",paddingBottom:12}}>{loading?"Buscando…":`${count} ventas / órdenes`}</caption><thead><tr><th>Fecha / número</th><th>Cliente / vehículo</th><th>Tipo / cobro</th><th>Total</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td data-label="Fecha / número"><Link href={`/orders/${r.id}`}><strong>{r.order_number}</strong></Link><div className="small muted">{fmtDate(r.sale_at)}</div></td><td data-label="Cliente / vehículo">{r.customer_name||"Mostrador"}<div className="small muted">{r.plate||"Sin vehículo"}</div></td><td data-label="Tipo / cobro">{r.kind}<div className="small muted">{r.payment_type}</div></td><td data-label="Total"><strong>{fmtRef(r.total_ref)}</strong><div className="small muted">{fmtVes(r.total_ves)}</div></td><td data-label="Estado"><span className={`pill ${r.status==='CLOSED'?'ok':r.status==='OPEN'?'warn':''}`}>{r.status==='CLOSED'?'Cerrada':r.status==='OPEN'?'Abierta':'Anulada'}</span>{r.cancellation_reason&&<div className="small muted">{r.cancellation_reason}</div>}</td><td data-label="Acciones"><div className="sales-actions"><Link className="btn btn-ghost" href={`/orders/${r.id}`}>Abrir</Link><Link className="btn btn-ghost" href={`/orders/${r.id}/receipt`}>Recibo 58 mm</Link><Link className="btn btn-ghost" href={`/orders/${r.id}/history`}>Historial</Link>{admin&&r.status==='CLOSED'&&<Link className="btn" href={`/orders/${r.id}/correct`}>Corregir</Link>}{admin&&r.status!=='CANCELLED'&&<button className="btn" onClick={()=>{setCancel(r);setReason("");setKeepAsBalance(false);}}>Anular</button>}</div></td></tr>)}</tbody></table>{!loading&&!rows.length&&<p className="muted">No hay ventas para estos filtros.</p>}</section>
  <div className="row-between"><button className="btn" disabled={page===0||loading} onClick={()=>setPage(x=>x-1)}>Anterior</button><span>Página {page+1} de {Math.max(1,Math.ceil(count/30))}</span><button className="btn" disabled={(page+1)*30>=count||loading} onClick={()=>setPage(x=>x+1)}>Siguiente</button></div>{!admin&&<p className="muted small">Las correcciones y anulaciones están disponibles en la cuenta propietaria.</p>}
 </main>;
}

