"use client";

import { use, useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type Account={id:string;name:string;currency:string;expected_native:number;actual_native:number|null;difference_native:number|null;explanation:string|null};type Data={business_date:string;status:string;accounts:Account[];closing:{closed_at:string|null;notes:string|null}|null};
export default function CashCloseReceipt({params}:{params:Promise<{date:string}>}){const {date}=use(params);const [data,setData]=useState<Data|null>(null);const [error,setError]=useState("");useEffect(()=>{supabase.rpc("cash_close_dashboard",{p_business_date:date}).then(({data,error})=>{if(error)setError(error.message);else setData(data as Data)})},[date]);if(error)return <main className="receipt-58"><div>{error}</div></main>;if(!data)return <main className="receipt-58"><div>Cargando…</div></main>;return <main className="receipt-58"><header><img src="/lubricenter-logo.png" alt="Lubricenter"/><strong>LUBRICENTER</strong><div>CUADRE DIARIO</div></header><div className="receipt-rule"/><div><strong>FECHA:</strong> {formatDate(data.business_date)}</div><div><strong>ESTADO:</strong> {data.status}</div>{data.closing?.closed_at&&<div><strong>CERRADO:</strong> {new Date(data.closing.closed_at).toLocaleString("es-VE")}</div>}<div className="receipt-rule"/>{data.accounts.map(a=><section key={a.id}><strong>{a.name}</strong><div className="receipt-line"><span>Esperado</span><span>{money(a.expected_native,a.currency)}</span></div><div className="receipt-line"><span>Real</span><span>{a.actual_native==null?"PENDIENTE":money(a.actual_native,a.currency)}</span></div><div className="receipt-line"><span>Diferencia</span><span>{a.difference_native==null?"—":money(a.difference_native,a.currency)}</span></div>{a.explanation&&<div>Nota: {a.explanation}</div>}<div className="receipt-rule"/></section>)}{data.closing?.notes&&<div>GENERAL: {data.closing.notes}</div>}<footer>Documento interno · Lubricenter OS</footer><button className="no-print btn btn-primary btn-block" onClick={()=>window.print()}>Imprimir</button></main>}
function money(n:number,c:string){return c==="USD"?`${n<0?"-":""}$${Math.abs(Number(n)).toFixed(2)}`:`${Number(n).toLocaleString("es-VE",{minimumFractionDigits:2,maximumFractionDigits:2})} Bs`}
function formatDate(v:string){return new Date(`${v}T12:00:00-04:00`).toLocaleDateString("es-VE")}
