'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { parseBdv, parseCashea, type Preview, type Provider } from '@/lib/finance/importers';
import { D, natures, type Nature } from '@/lib/finance/money';

type Source = { id: string; name: string; provider: Provider; external_account: string };
type Case = { id: string; kind: string; subject_id: string; subject_type: string; title: string; explanation: string; evidence: Record<string, unknown> };
type Batch = { id: string; source_id: string; source_name: string; status: string; requested_from: string; requested_to: string; row_count: number; balance_chain: boolean | null };
type Data = { users: {id:string;email:string;role:string}[]; rules: {id:string;description_contains:string;nature:string}[]; role: string; total: number; cases: Case[]; sources: Source[]; batches: Batch[]; accounts: { id: string; code: string; name: string; currency: string }[] };
type Review = { transaction: { id: string; occurred_at: string; description: string; reference: string; external_order: string | null; amount: string; amount_ref: string | null; assigned_ref: string | null; currency: string; ownership_status: string; ownership_reason: string; direction: string; nature: Nature; raw: Record<string, unknown> }; targets: { id: string; kind: string; amount: string; remaining: string; currency: string; reference?: string; installment_no?: number; occurred_at?: string }[]; allocations: { id: string; external_amount: string; target_amount: string; difference: string; reason: string; reversed_at: string | null }[]; history: { id: string; event_type: string; created_at: string }[] };
const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Caracas' }).format(new Date());
const labels: Record<Provider, string> = { BDV: 'Banco de Venezuela · pegar movimientos', CASHEA_TRANSACTIONS: 'Cashea · cobros (export.xlsx)', CASHEA_ORDERS: 'Cashea · órdenes (ordenes.xlsx)' };

export default function FinanceInbox() {
  const [data, setData] = useState<Data | null>(null), [role, setRole] = useState(''), [offset, setOffset] = useState(0);
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [tab, setTab] = useState<'inbox' | 'import' | 'setup'>('inbox');
  const [selected, setSelected] = useState<Case | null>(null), [review, setReview] = useState<Review | null>(null), [batch, setBatch] = useState<Batch | null>(null);
  async function load() {
    const r = await supabase.rpc('finance_role'); if (r.error) throw new Error('Finance Core está pendiente de activar en esta base. No se modificaron los datos.');
    setRole(r.data);
    if (r.data === 'OPERATOR') return;
    const res = await supabase.rpc('finance_inbox', { p_offset: offset }); if (res.error) throw res.error; setData(res.data);
  }
  useEffect(() => { load().catch(e => setError(e.message)); }, [offset]);
  async function run(action: () => Promise<void>) {
    if (busy) return; setBusy(true); setError(''); setNotice('');
    try { await action(); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  async function refresh() { const r = await supabase.rpc('finance_reconcile'); if (r.error) throw r.error; setNotice(`${r.data.matched} coincidencias nuevas. Solo se muestran asuntos pendientes.`); }
  async function open(c: Case) {
    setSelected(c); setReview(null);
    if (c.subject_type === 'external_transaction') { const r = await supabase.rpc('finance_review', { p_id: c.subject_id }); if (r.error) throw r.error; setReview(r.data); }
    if (c.subject_type === 'import_batch') setBatch(data?.batches.find(b => b.id === c.subject_id) ?? null);
  }
  return <main className="container stack finance-inbox">
    <section className="brand-hero"><div><div className="eyebrow">FINANCE CORE</div><h1>Revisión financiera</h1><p>Resuelve excepciones. Las ventas y la atención pueden continuar.</p></div><Link href="/cash-close" className="btn">Contar efectivo</Link></section>
    {error && <div className="error" role="alert">{error}</div>}{notice && <div className="success" role="status">{notice}</div>}
    {role === 'OPERATOR' ? <section className="card stack"><h2>Tu tarea diaria</h2><p>Registra los cobros con su referencia y cuenta Caja USD y Caja Bs al finalizar. El administrador revisa bancos y Cashea.</p><Link href="/cash-close" className="btn btn-primary">Cuadre de caja</Link><Link href="/orders/new" className="btn">Nueva orden</Link></section> : data && <>
      <nav className="row" aria-label="Herramientas financieras"><button className={`btn ${tab === 'inbox' ? 'btn-primary' : ''}`} onClick={() => setTab('inbox')}>Pendientes · {data.total}</button><button className={`btn ${tab === 'import' ? 'btn-primary' : ''}`} onClick={() => setTab('import')}>Importar reporte</button>{role === 'OWNER' && <button className="btn" onClick={() => setTab('setup')}>Configuración</button>}<button className="btn" disabled={busy} onClick={() => run(refresh)}>{busy ? 'Procesando…' : 'Conciliar ahora'}</button></nav>
      {tab === 'inbox' && <section className="stack" aria-label="Excepciones">
        {!data.total && <div className="card stack"><h2>Sin excepciones abiertas</h2><p>Esto no certifica períodos aún no importados. Puedes revisar la cobertura en Importar reporte.</p></div>}
        {data.cases.map(c => <article key={c.id} className="card row-between"><div><h2 className="section-title">{c.title}</h2><p>{c.explanation}</p></div><button className="btn btn-primary" disabled={busy} onClick={() => run(() => open(c))}>Revisar</button></article>)}
        {data.total > 50 && <div className="row"><button className="btn" disabled={!offset} onClick={() => setOffset(Math.max(0, offset - 50))}>Anterior</button><span>{offset + 1}–{Math.min(offset + 50, data.total)} de {data.total}</span><button className="btn" disabled={offset + 50 >= data.total} onClick={() => setOffset(offset + 50)}>Siguiente</button></div>}
      </section>}
      {tab === 'import' && <><ImportForm sources={data.sources} busy={busy} run={run} onDone={async () => { await refresh(); }} />
        <section className="card stack"><h2>Cobertura de reportes</h2><p>Un reporte importado puede ayudar a conciliar aunque su cobertura todavía esté pendiente.</p>{data.batches.map(b => <div className="row-between" key={b.id}><div><strong>{b.source_name}</strong><div>{b.requested_from} → {b.requested_to} · {b.row_count} filas</div></div>{b.status === 'COMPLETE' ? <span className="pill ok">Cobertura verificada</span> : <button className="btn" onClick={() => { setBatch(b); setSelected(null); setReview(null); }}>Verificar cobertura</button>}</div>)}</section></>}
      {tab === 'setup' && role === 'OWNER' && <Settings data={data} busy={busy} run={run} />}
      {batch && <Coverage key={batch.id} batch={batch} busy={busy} run={run} onClose={() => setBatch(null)} onDone={async () => { setBatch(null); setSelected(null); await refresh(); }} />}
      {selected && !batch && <section className="card stack" aria-label="Detalle de excepción"><div className="row-between"><h2>{selected.title}</h2><button className="btn" onClick={() => { setSelected(null); setReview(null); }}>Cerrar detalle</button></div>
        {selected.kind === "OUTFLOW_NATURE" && <InternalNature caseId={selected.subject_id} busy={busy} run={run} onDone={async () => { setSelected(null); await refresh(); }} />}{review ? <ReviewPanel key={review.transaction.id} review={review} busy={busy} run={run} onDone={async () => { await refresh(); await open(selected); }} /> : <><p>{selected.explanation}</p>{selected.subject_type === 'cash_closing' ? <Link className="btn" href="/cash-close">Revisar conteo de caja</Link> : selected.subject_type === 'cashea_sale' ? <Link className="btn" href="/cashea">Revisar orden Cashea</Link> : <Link className="btn" href="/cash">Revisar movimiento interno</Link>}<details><summary>Evidencia</summary><pre>{JSON.stringify(selected.evidence, null, 2)}</pre></details></>}
      </section>}
    </>}
    <Link href="/finance" className="btn btn-ghost">← Central financiera</Link>
  </main>;
}

function ImportForm({ sources, busy, run, onDone }: { sources: Source[]; busy: boolean; run: (f: () => Promise<void>) => void; onDone: () => Promise<void> }) {
  const [source, setSource] = useState(sources[0]?.id ?? ''), [text, setText] = useState(''), [from, setFrom] = useState(today()), [to, setTo] = useState(today()), [preview, setPreview] = useState<Preview | null>(null), [name, setName] = useState('Movimientos BDV');
  const selected = sources.find(s => s.id === source);
  async function file(file?: File) {
    if (!file || !selected) return;
    setPreview(null);
    if (!file.name.toLowerCase().endsWith('.xlsx') || file.size > 8 * 1024 * 1024) throw new Error('Usa un archivo XLSX de hasta 8 MB.');
    const { readSheet } = await import('read-excel-file/browser');
    const cells = await readSheet(file, { parseNumber: value => value });
    setPreview(parseCashea(cells, selected.provider as 'CASHEA_TRANSACTIONS' | 'CASHEA_ORDERS')); setName(file.name);
  }
  return <section className="card stack"><h2>Traer movimientos</h2>{!sources.length ? <p>El dueño debe configurar primero Banco de Venezuela y las fuentes Cashea.</p> : <>
    <label>Origen<select className="select" value={source} onChange={e => { setSource(e.target.value); setPreview(null); }} disabled={busy}>{sources.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
    <div className="grid grid-2"><label>Desde<input className="input" type="date" value={from} max={to} onChange={e => setFrom(e.target.value)} /></label><label>Hasta<input className="input" type="date" value={to} min={from} max={today()} onChange={e => setTo(e.target.value)} /></label></div>
    {selected?.provider === 'BDV' ? <><label>Copia todas las páginas del período, con encabezados y saldos<textarea className="textarea" rows={8} value={text} onChange={e => { setText(e.target.value); setPreview(null); }} placeholder="Fecha · Referencia · Descripción · Débito / Crédito · Monto · Saldo" /></label><button className="btn" disabled={busy || !text.trim()} onClick={() => { setPreview(parseBdv(text)); setName('Movimientos BDV'); }}>Revisar datos pegados</button></> : <label>{selected && labels[selected.provider]}<input className="input" type="file" accept=".xlsx" disabled={busy} onChange={e => run(() => file(e.target.files?.[0]))} /></label>}
    {preview && <div className="stack"><div className="card"><strong>{preview.rows.length + preview.orders.length} filas válidas · {preview.duplicates} duplicadas omitidas</strong><p>{preview.observed_from} → {preview.observed_to}</p>{preview.balance_chain !== null && <span>Secuencia de saldos: {preview.balance_chain ? 'coherente' : 'con saltos'}</span>}</div>
      {!!preview.errors.length && <div className="error">Corrige {preview.errors.length} errores antes de importar: {preview.errors.slice(0, 5).map(e => `fila ${e.row}: ${e.message}`).join(' · ')}</div>}
      {!!preview.warnings.length && <div className="finance-warning card">{preview.warnings.length} observaciones. Se conservarán para revisión: {preview.warnings.slice(0, 3).map(e => `fila ${e.row}: ${e.message}`).join(' · ')}</div>}
      <p>Importar conserva evidencia. No registra ventas ni suma cobros otra vez.</p>
      <button className="btn btn-primary" disabled={busy || !!preview.errors.length || !from || !to} onClick={() => run(async () => { const r = await supabase.rpc('finance_import', { p_source_id: source, p_name: name, p_from: from, p_to: to, p_preview: preview }); if (r.error) throw r.error; setPreview(null); setText(''); await onDone(); })}>{busy ? 'Importando…' : 'Importar y conciliar'}</button>
    </div>}
  </>}</section>;
}

function Coverage({ batch, busy, run, onClose, onDone }: { batch: Batch; busy: boolean; run: (f: () => Promise<void>) => void; onClose: () => void; onDone: () => Promise<void> }) {
  const [count, setCount] = useState(''), [total, setTotal] = useState(''), [opening, setOpening] = useState(''), [closing, setClosing] = useState(''), [evidence, setEvidence] = useState(''), [checked, setChecked] = useState(false);
  return <section className="card stack"><div className="row-between"><h2>Verificar {batch.source_name}</h2><button className="btn" onClick={onClose}>Cerrar</button></div><p>{batch.requested_from} → {batch.requested_to}. Usa controles de la consulta o estado oficial, no copies los totales calculados por este importador.</p>
    <div className="grid grid-2"><label>Total de filas del reporte completo<input className="input" type="number" min="0" value={count} onChange={e => setCount(e.target.value)} /></label><label>Suma de importes (BDV: entradas + salidas absolutas en Bs; Cashea: USD)<input className="input" inputMode="decimal" value={total} onChange={e => setTotal(e.target.value)} placeholder="Decimal con punto" /></label>
      {batch.balance_chain !== null && <><label>Saldo antes del primer movimiento<input className="input" inputMode="decimal" value={opening} onChange={e => setOpening(e.target.value)} /></label><label>Saldo después del último<input className="input" inputMode="decimal" value={closing} onChange={e => setClosing(e.target.value)} /></label></>}
    </div><label>De dónde comprobaste estos controles<textarea className="textarea" value={evidence} onChange={e => setEvidence(e.target.value)} placeholder="Ej.: estado oficial del período, número de páginas y totales de la consulta" /></label><label className="row"><input type="checkbox" checked={checked} onChange={e => setChecked(e.target.checked)} />Confirmé que están todas las páginas y que el control corresponde a estas fechas.</label>
    <button className="btn btn-primary" disabled={busy || !checked || !count || !total || evidence.trim().length < 10} onClick={() => run(async () => { const r = await supabase.rpc('finance_verify_batch', { p_id: batch.id, p_controls: { from: batch.requested_from, to: batch.requested_to, expected_count: Number(count), expected_total: total, opening: opening || null, closing: closing || null, evidence, all_pages: checked } }); if (r.error) throw r.error; await onDone(); })}>Verificar controles</button>
  </section>;
}

function ReviewPanel({ review, busy, run, onDone }: { review: Review; busy: boolean; run: (f: () => Promise<void>) => void; onDone: () => Promise<void> }) {
  const x = review.transaction;
  const [requestId, setRequestId] = useState(() => crypto.randomUUID());
  const [reason, setReason] = useState(''), [ownership, setOwnership] = useState(x.ownership_status), [nature, setNature] = useState<Nature>('UNCLASSIFIED'), [category, setCategory] = useState(''), [target, setTarget] = useState(''), [amount, setAmount] = useState('');
  const remaining = new D(x.amount_ref ? D.min(x.amount_ref, x.assigned_ref ?? x.amount_ref) : x.amount).sub(review.allocations.filter(a => !a.reversed_at).reduce((s, a) => s.add(a.external_amount), new D(0))).toFixed(8);
  async function resolve(action: string, id: string, data: Record<string, unknown>) { const r = await supabase.rpc('finance_resolve', { p_action: action, p_id: id, p_data: { ...data, reason } }); if (r.error) throw r.error; await onDone(); }
  return <div className="stack"><p><strong>{x.description}</strong> · {x.occurred_at} · Ref. {x.reference}{x.external_order && ` · Orden Cashea ${x.external_order}`}</p><p>Importe: {x.amount} {x.currency} · Pendiente de vincular: {remaining} {x.amount_ref ? 'USD' : x.currency}</p>
    <label>Motivo para el historial<input className="input" value={reason} onChange={e => setReason(e.target.value)} placeholder="Qué comprobaste y por qué tomas esta decisión" /></label>
    {x.external_order && <div className="grid grid-2"><label>¿A quién pertenece?<select className="select" value={ownership} onChange={e => setOwnership(e.target.value)}><option value="UNRESOLVED">Todavía no lo sé</option><option value="OWN">Lubricenter</option><option value="OTHER_LOCATION">Otro local</option></select></label><button className="btn" disabled={busy || reason.trim().length < 5} onClick={() => run(() => resolve('OWNERSHIP', x.id, { status: ownership }))}>Guardar propiedad</button></div>}
    {x.direction === 'OUT' && <div className="stack"><label>Primero, ¿qué tipo de salida es?<select className="select" value={nature} onChange={e => setNature(e.target.value as Nature)}>{Object.entries(natures).map(([v, label]) => <option value={v} key={v}>{label}</option>)}</select></label>{['EXPENSE', 'BANK_FEE'].includes(nature) && <label>Categoría<input className="input" value={category} onChange={e => setCategory(e.target.value)} /></label>}<button className="btn" disabled={busy || reason.trim().length < 5} onClick={() => run(() => resolve('CLASSIFY', x.id, { nature, category }))}>Guardar clasificación</button><p>Clasificar explica la evidencia externa. Vincula también su registro interno para evitar registrar dos veces la salida.</p><div className="row"><Link href="/expenses" className="btn">Compras y proveedores</Link><Link href="/cash" className="btn">Caja y transferencias</Link></div></div>}
    {x.ownership_status === 'OWN' && new D(remaining).gt(0) && <fieldset disabled={busy} className="stack"><legend>Vincular importe comprobado</legend><label>Registro interno<select className="select" value={target} onChange={e => { setTarget(e.target.value); const t = review.targets.find(t => t.id === e.target.value); setAmount(t ? D.min(t.remaining, remaining).toFixed(8) : ''); }}><option value="">Selecciona una coincidencia</option>{review.targets.filter(t => new D(t.remaining).gt(0)).map(t => <option key={t.id} value={t.id}>{t.kind === 'initial' ? 'Inicial Cashea' : t.kind === 'installment' ? `Cuota ${t.installment_no}` : `${t.occurred_at?.slice(0, 10)} · Ref. ${t.reference || 'sin referencia'}`} · disponible {t.remaining} {t.currency}</option>)}</select></label><label>Monto a vincular<input className="input" inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} /></label><button className="btn btn-primary" disabled={!target || !amount || reason.trim().length < 5} onClick={() => run(async () => { const t = review.targets.find(t => t.id === target)!; const r = await supabase.rpc('finance_allocate', { p_request_id: requestId, p_external_id: x.id, p_movement_id: t.kind === 'movement' ? t.id : null, p_installment_id: t.kind === 'installment' ? t.id : null, p_sale_id: t.kind === 'initial' ? t.id : null, p_external_amount: amount, p_target_amount: amount, p_method: 'MANUAL', p_reason: reason }); if (r.error) throw r.error; setRequestId(crypto.randomUUID()); setTarget(''); setAmount(''); await onDone(); })}>Vincular sin volver a registrar dinero</button><p className="muted">Si falta el registro, créalo desde su módulo. Si no estás seguro, puedes dejar este caso pendiente.</p></fieldset>}
    {x.direction === 'OUT' && !x.external_order && ['EXPENSE','ASSET_PURCHASE','OWNER_DRAW','TAX','BANK_FEE'].includes(x.nature) && new D(remaining).gt(0) && <section className="card stack"><strong>Si esta salida todavía no está registrada</strong><p>Revisa primero las coincidencias de arriba. Este botón registrará la salida una sola vez y la vinculará al banco.</p><button className="btn" disabled={busy || reason.trim().length < 5} onClick={() => run(async () => { const r = await supabase.rpc('finance_record_external_outflow', { p_id: x.id, p_reason: reason }); if (r.error) throw r.error; await onDone(); })}>Confirmo que falta: registrar salida desde el banco</button></section>}
    {!!review.allocations.length && <div className="stack"><h3>Asignaciones e historial</h3>{review.allocations.map(a => <div key={a.id} className="card"><strong>{a.external_amount}</strong> → {a.target_amount} · diferencia {a.difference}<p>{a.reason}</p>{a.reversed_at ? <span>Revertida · {a.reversed_at}</span> : <button className="btn" disabled={busy || reason.trim().length < 5} onClick={() => run(() => resolve('REVERSE_ALLOCATION', a.id, {}))}>Revertir con motivo</button>}</div>)}</div>}
    <details><summary>Evidencia original y trazabilidad</summary><p>ID estable: {x.id} · Propiedad: {x.ownership_reason}</p><pre>{JSON.stringify(x.raw, null, 2)}</pre>{review.history.map(h => <p key={h.id}>{h.created_at} · {h.event_type}</p>)}</details>
  </div>;
}

function Settings({ data, busy, run }: { data: Data; busy: boolean; run: (f: () => Promise<void>) => void }) {
  const [provider, setProvider] = useState<Provider>('BDV'), [accountName, setAccountName] = useState(''), [rule, setRule] = useState(''), [category, setCategory] = useState(''), [uid, setUid] = useState(''), [role, setRole] = useState('OPERATOR');
  async function configure(action: string, value: Record<string, unknown>) { const r = await supabase.rpc('finance_configure', { p_action: action, p_data: value }); if (r.error) throw r.error; }
  return <div className="stack"><section className="card stack"><h2>Fuentes externas</h2><label>Tipo<select className="select" value={provider} onChange={e => setProvider(e.target.value as Provider)}>{Object.entries(labels).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select></label>{provider === 'BDV' && <label>Identificador de la cuenta (sin credenciales)<input className="input" value={accountName} onChange={e => setAccountName(e.target.value)} /></label>}<button className="btn btn-primary" disabled={busy || (provider === 'BDV' && !accountName.trim()) || data.sources.some(s => s.provider === provider)} onClick={() => run(() => configure('SOURCE', { provider, name: labels[provider], external_account: provider === 'BDV' ? accountName.trim() : provider, currency: provider === 'BDV' ? 'VES' : 'USD', account_id: provider === 'BDV' ? data.accounts.find(a => a.code === 'BDV')?.id : null }))}>{data.sources.some(s => s.provider === provider) ? 'Fuente ya configurada' : 'Agregar fuente'}</button><p>Cashea puede traer varias cuentas y monedas en un mismo archivo. Cada fila conserva esos datos; la propiedad de la venta se resuelve por el número de orden o con evidencia.</p></section>
    <section className="card stack"><h2>Regla aprobada de comisión bancaria</h2><label>Descripción contiene<input className="input" value={rule} onChange={e => setRule(e.target.value)} placeholder="COMISION PAGOMOVILBDV" /></label><label>Categoría<input className="input" value={category} onChange={e => setCategory(e.target.value)} placeholder="Comisiones bancarias" /></label><button className="btn" disabled={busy || rule.trim().length < 6 || !category.trim()} onClick={() => run(() => configure('RULE', { source_id: data.sources.find(s => s.provider === 'BDV')?.id, description_contains: rule, nature: 'BANK_FEE', category }))}>Aprobar regla explícita</button><p>La regla clasifica evidencia. No crea gastos ni aprende cambios sin aprobación.</p>{data.rules.map(r => <div key={r.id} className="row-between"><span>{r.description_contains}</span><button className="btn" disabled={busy} onClick={() => run(() => configure("DISABLE_RULE", {id:r.id}))}>Desactivar regla</button></div>)}</section>
    <section className="card stack"><h2>Acceso financiero</h2><label>Usuario<select className="select" value={uid} onChange={e => setUid(e.target.value)}><option value="">Selecciona un usuario</option>{data.users.map(u => <option key={u.id} value={u.id}>{u.email} · {u.role === "ADMIN" ? "Administrador" : "Operador"}</option>)}</select></label><label>Rol<select className="select" value={role} onChange={e => setRole(e.target.value)}><option value="OPERATOR">Operador: cobros y conteo</option><option value="ADMIN">Administrador: conciliación y excepciones</option></select></label><button className="btn" disabled={busy || !uid} onClick={() => run(() => configure('MEMBERSHIP', { user_id: uid, role }))}>Guardar acceso</button><p>Solo el dueño configura fuentes, reglas, accesos y retiros.</p></section>
  </div>;
}

function InternalNature({caseId,busy,run,onDone}:{caseId:string;busy:boolean;run:(f:()=>Promise<void>)=>void;onDone:()=>Promise<void>}) {
 const [nature,setNature]=useState<Nature>('UNCLASSIFIED'),[category,setCategory]=useState(''),[reason,setReason]=useState('');
 return <div className="stack"><label>Naturaleza<select className="select" value={nature} onChange={e=>setNature(e.target.value as Nature)}>{Object.entries(natures).filter(([k])=>['EXPENSE','ASSET_PURCHASE','OWNER_DRAW','TAX','BANK_FEE','UNCLASSIFIED'].includes(k)).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>{['EXPENSE','BANK_FEE'].includes(nature)&&<label>Categoría<input className="input" value={category} onChange={e=>setCategory(e.target.value)}/></label>}<label>Motivo<input className="input" value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="btn btn-primary" disabled={busy||reason.trim().length<5||nature==='UNCLASSIFIED'} onClick={()=>run(async()=>{const r=await supabase.rpc('finance_resolve',{p_action:'CLASSIFY_MOVEMENT',p_id:caseId,p_data:{nature,category,reason}});if(r.error)throw r.error;await onDone();})}>Clasificar salida registrada</button></div>;
}
